name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code aus Repository laden
        uses: actions/checkout@v4

      - name: Python-Umgebung einrichten
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unit-Tests ausführen
        run: pytest

      - name: Docker installieren
        run: |
          sudo apt-get update
          sudo apt-get install docker.io
          docker --version

      - name: Docker Build
        run: docker build -t mein-app .

      - name: Docker Container testen
        run: docker run --rm mein-app

      - name: Docker Image pushen
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker tag mein-app dein-dockerhub-benutzername/mein-app:latest
          docker push dein-dockerhub-benutzername/mein-app:latest
